/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 suit.glb --transform --shadows --keepmaterials --keepmeshes --keepnames 
Files: suit.glb [266.18KB] > C:\Users\abhishek\Desktop\CustomSuitConfigurator\public\suit-transformed.glb [188.56KB] (29%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";

export function Suit(props) {
  const { nodes, materials } = useGLTF("/suit-transformed.glb");
  const path = "/blueTexture.jpg";
  const material = useLoader(TextureLoader, path);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2Button_Curved"].geometry}
        // material={materials["default.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial roughness={1}  map={material} />
      </mesh>
      <mesh
        name="button"
        castShadow
        receiveShadow
        geometry={nodes.S4.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Button_Hole.geometry}
        // material={materials["Material.066"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.S14_4001.geometry}
        // material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.045}
      />
      <mesh
        name="back"
        castShadow
        receiveShadow
        geometry={nodes.NoVent.geometry}
        // material={materials["default.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial map={material} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/suit-transformed.glb");
